<?php
/**
 * BulkSMS SaaS Platform Configuration
 * This file is auto-generated by the installer.
 */

// Application
define('APP_NAME', 'BulkSMS Pro');
define('APP_URL', 'http://localhost');
define('APP_DEBUG', false);
define('APP_TIMEZONE', 'UTC');
define('APP_VERSION', '1.0.0');
define('APP_ENV', 'production');

// Database
define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', 'bulksms');
define('DB_USER', 'root');
define('DB_PASS', '');

// Security
define('APP_KEY', ''); // Auto-generated during installation
define('HASH_COST', 12);

// Session
define('SESSION_LIFETIME', 7200);

// Mail (for email notifications & OTP)
define('MAIL_DRIVER', 'smtp');
define('MAIL_HOST', '');
define('MAIL_PORT', 587);
define('MAIL_USERNAME', '');
define('MAIL_PASSWORD', '');
define('MAIL_ENCRYPTION', 'tls');
define('MAIL_FROM_ADDRESS', '');
define('MAIL_FROM_NAME', APP_NAME);

// Rate Limiting
define('RATE_LIMIT_ENABLED', true);
define('RATE_LIMIT_REQUESTS', 60);
define('RATE_LIMIT_WINDOW', 60);

// Upload
define('MAX_UPLOAD_SIZE', 10 * 1024 * 1024); // 10MB
define('ALLOWED_UPLOAD_TYPES', 'csv,xlsx,xls,txt');

// Queue
define('QUEUE_BATCH_SIZE', 100);
define('QUEUE_RETRY_ATTEMPTS', 3);
define('QUEUE_RETRY_DELAY', 60);

// SMS
define('SMS_MAX_LENGTH', 160);
define('SMS_UNICODE_MAX_LENGTH', 70);
define('SMS_MULTIPART_LENGTH', 153);
define('SMS_UNICODE_MULTIPART_LENGTH', 67);
