<?php
/**
 * BulkSMS SaaS Platform - Auto Installer
 * Step-by-step installation wizard for cPanel hosting
 */

define('ROOT_PATH', dirname(__DIR__));
define('INSTALL_PATH', __DIR__);
define('APP_PATH', ROOT_PATH . '/app');
define('STORAGE_PATH', ROOT_PATH . '/storage');

// Check if already installed
if (file_exists(APP_PATH . '/Config/installed.lock')) {
    echo '<!DOCTYPE html><html><head><title>Already Installed</title></head><body>';
    echo '<div style="text-align:center;margin-top:100px;font-family:Arial">';
    echo '<h2>BulkSMS Pro is already installed</h2>';
    echo '<p>If you need to reinstall, please delete <code>app/Config/installed.lock</code></p>';
    echo '<a href="../public/">Go to Application</a>';
    echo '</div></body></html>';
    exit;
}

session_start();

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$step = max(1, min(5, $step));
$errors = [];
$success = '';

// Process POST requests
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    switch ($step) {
        case 2:
            // Server requirements check - auto proceed
            break;
        case 3:
            // Database configuration
            $dbHost = trim($_POST['db_host'] ?? 'localhost');
            $dbPort = trim($_POST['db_port'] ?? '3306');
            $dbName = trim($_POST['db_name'] ?? '');
            $dbUser = trim($_POST['db_user'] ?? '');
            $dbPass = $_POST['db_pass'] ?? '';

            if (empty($dbName) || empty($dbUser)) {
                $errors[] = 'Database name and username are required';
            } else {
                try {
                    $dsn = "mysql:host={$dbHost};port={$dbPort};charset=utf8mb4";
                    $pdo = new PDO($dsn, $dbUser, $dbPass, [
                        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
                    ]);

                    // Create database if not exists
                    $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                    $pdo->exec("USE `{$dbName}`");

                    // Import schema
                    $schemaFile = ROOT_PATH . '/database/schema.sql';
                    if (!file_exists($schemaFile)) {
                        $errors[] = 'Schema file not found at database/schema.sql';
                    } else {
                        $sql = file_get_contents($schemaFile);
                        $pdo->exec($sql);

                        // Store in session for config creation
                        $_SESSION['install_db'] = [
                            'host' => $dbHost,
                            'port' => $dbPort,
                            'name' => $dbName,
                            'user' => $dbUser,
                            'pass' => $dbPass
                        ];

                        header('Location: ?step=4');
                        exit;
                    }
                } catch (PDOException $e) {
                    $errors[] = 'Database error: ' . $e->getMessage();
                }
            }
            break;
        case 4:
            // Admin account creation
            $adminName = trim($_POST['admin_name'] ?? '');
            $adminEmail = trim($_POST['admin_email'] ?? '');
            $adminPass = $_POST['admin_password'] ?? '';
            $adminPassConfirm = $_POST['admin_password_confirm'] ?? '';
            $siteUrl = rtrim(trim($_POST['site_url'] ?? ''), '/');
            $siteName = trim($_POST['site_name'] ?? 'BulkSMS Pro');

            if (empty($adminName)) $errors[] = 'Admin name is required';
            if (empty($adminEmail) || !filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) $errors[] = 'Valid email is required';
            if (strlen($adminPass) < 8) $errors[] = 'Password must be at least 8 characters';
            if ($adminPass !== $adminPassConfirm) $errors[] = 'Passwords do not match';
            if (empty($siteUrl)) $errors[] = 'Site URL is required';

            if (empty($errors) && !empty($_SESSION['install_db'])) {
                $db = $_SESSION['install_db'];
                $appKey = bin2hex(random_bytes(32));

                // Create config file
                $configContent = "<?php\n";
                $configContent .= "/**\n * BulkSMS SaaS Platform Configuration\n * Auto-generated by installer on " . date('Y-m-d H:i:s') . "\n */\n\n";
                $configContent .= "// Application\n";
                $configContent .= "define('APP_NAME', " . var_export($siteName, true) . ");\n";
                $configContent .= "define('APP_URL', " . var_export($siteUrl, true) . ");\n";
                $configContent .= "define('APP_DEBUG', false);\n";
                $configContent .= "define('APP_TIMEZONE', 'UTC');\n";
                $configContent .= "define('APP_VERSION', '1.0.0');\n";
                $configContent .= "define('APP_ENV', 'production');\n\n";
                $configContent .= "// Database\n";
                $configContent .= "define('DB_HOST', " . var_export($db['host'], true) . ");\n";
                $configContent .= "define('DB_PORT', " . var_export($db['port'], true) . ");\n";
                $configContent .= "define('DB_NAME', " . var_export($db['name'], true) . ");\n";
                $configContent .= "define('DB_USER', " . var_export($db['user'], true) . ");\n";
                $configContent .= "define('DB_PASS', " . var_export($db['pass'], true) . ");\n\n";
                $configContent .= "// Security\n";
                $configContent .= "define('APP_KEY', '{$appKey}');\n";
                $configContent .= "define('HASH_COST', 12);\n\n";
                $configContent .= "// Session\ndefine('SESSION_LIFETIME', 7200);\n\n";
                $configContent .= "// Mail\n";
                $configContent .= "define('MAIL_DRIVER', 'smtp');\ndefine('MAIL_HOST', '');\ndefine('MAIL_PORT', 587);\n";
                $configContent .= "define('MAIL_USERNAME', '');\ndefine('MAIL_PASSWORD', '');\ndefine('MAIL_ENCRYPTION', 'tls');\n";
                $configContent .= "define('MAIL_FROM_ADDRESS', " . var_export($adminEmail, true) . ");\n";
                $configContent .= "define('MAIL_FROM_NAME', " . var_export($siteName, true) . ");\n\n";
                $configContent .= "// Rate Limiting\ndefine('RATE_LIMIT_ENABLED', true);\ndefine('RATE_LIMIT_REQUESTS', 60);\ndefine('RATE_LIMIT_WINDOW', 60);\n\n";
                $configContent .= "// Upload\ndefine('MAX_UPLOAD_SIZE', 10 * 1024 * 1024);\ndefine('ALLOWED_UPLOAD_TYPES', 'csv,xlsx,xls,txt');\n\n";
                $configContent .= "// Queue\ndefine('QUEUE_BATCH_SIZE', 100);\ndefine('QUEUE_RETRY_ATTEMPTS', 3);\ndefine('QUEUE_RETRY_DELAY', 60);\n\n";
                $configContent .= "// SMS\ndefine('SMS_MAX_LENGTH', 160);\ndefine('SMS_UNICODE_MAX_LENGTH', 70);\n";
                $configContent .= "define('SMS_MULTIPART_LENGTH', 153);\ndefine('SMS_UNICODE_MULTIPART_LENGTH', 67);\n";

                if (!file_put_contents(APP_PATH . '/Config/config.php', $configContent)) {
                    $errors[] = 'Failed to create config file. Check permissions on app/Config/';
                } else {
                    // Create admin account
                    try {
                        $dsn = "mysql:host={$db['host']};port={$db['port']};dbname={$db['name']};charset=utf8mb4";
                        $pdo = new PDO($dsn, $db['user'], $db['pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

                        $uuid = sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
                            mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff),
                            mt_rand(0, 0x0fff) | 0x4000, mt_rand(0, 0x3fff) | 0x8000,
                            mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff));

                        $stmt = $pdo->prepare("INSERT INTO users (uuid, name, email, password, role, status, email_verified_at, sms_balance, created_at, updated_at) VALUES (?, ?, ?, ?, 'super_admin', 'active', NOW(), 99999, NOW(), NOW())");
                        $stmt->execute([$uuid, $adminName, $adminEmail, password_hash($adminPass, PASSWORD_BCRYPT, ['cost' => 12])]);

                        // Create installation lock
                        file_put_contents(APP_PATH . '/Config/installed.lock', date('Y-m-d H:i:s'));

                        // Clean up session
                        unset($_SESSION['install_db']);

                        header('Location: ?step=5');
                        exit;
                    } catch (PDOException $e) {
                        $errors[] = 'Failed to create admin account: ' . $e->getMessage();
                    }
                }
            }
            break;
    }
}

// Check server requirements
function checkRequirements(): array
{
    $checks = [];
    $checks[] = ['name' => 'PHP Version (8.0+)', 'status' => version_compare(PHP_VERSION, '8.0.0', '>='), 'current' => PHP_VERSION];
    $checks[] = ['name' => 'PDO Extension', 'status' => extension_loaded('pdo'), 'current' => extension_loaded('pdo') ? 'Loaded' : 'Not loaded'];
    $checks[] = ['name' => 'PDO MySQL', 'status' => extension_loaded('pdo_mysql'), 'current' => extension_loaded('pdo_mysql') ? 'Loaded' : 'Not loaded'];
    $checks[] = ['name' => 'cURL Extension', 'status' => extension_loaded('curl'), 'current' => extension_loaded('curl') ? 'Loaded' : 'Not loaded'];
    $checks[] = ['name' => 'JSON Extension', 'status' => extension_loaded('json'), 'current' => extension_loaded('json') ? 'Loaded' : 'Not loaded'];
    $checks[] = ['name' => 'OpenSSL Extension', 'status' => extension_loaded('openssl'), 'current' => extension_loaded('openssl') ? 'Loaded' : 'Not loaded'];
    $checks[] = ['name' => 'Mbstring Extension', 'status' => extension_loaded('mbstring'), 'current' => extension_loaded('mbstring') ? 'Loaded' : 'Not loaded'];
    $checks[] = ['name' => 'FileInfo Extension', 'status' => extension_loaded('fileinfo'), 'current' => extension_loaded('fileinfo') ? 'Loaded' : 'Not loaded'];
    $checks[] = ['name' => 'GD Extension', 'status' => extension_loaded('gd'), 'current' => extension_loaded('gd') ? 'Loaded' : 'Not loaded'];

    $dirs = ['storage/logs', 'storage/cache', 'storage/backups', 'storage/uploads', 'storage/sessions', 'storage/temp', 'app/Config'];
    foreach ($dirs as $dir) {
        $path = ROOT_PATH . '/' . $dir;
        $writable = is_dir($path) && is_writable($path);
        $checks[] = ['name' => "{$dir} (writable)", 'status' => $writable, 'current' => $writable ? 'Writable' : 'Not writable'];
    }

    return $checks;
}

$allPassed = true;
if ($step === 2) {
    $requirements = checkRequirements();
    foreach ($requirements as $req) {
        if (!$req['status']) $allPassed = false;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BulkSMS Pro - Installation Wizard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-primary: #0a0a0f;
            --bg-secondary: #12121a;
            --bg-card: #1a1a2e;
            --bg-card-hover: #1e1e35;
            --border-color: rgba(255,255,255,0.06);
            --text-primary: #e8e8ed;
            --text-secondary: #8e8ea0;
            --accent: #6366f1;
            --accent-glow: rgba(99,102,241,0.3);
            --success: #22c55e;
            --danger: #ef4444;
            --warning: #f59e0b;
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Inter', -apple-system, system-ui, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        .installer-container {
            width: 100%;
            max-width: 680px;
        }
        .installer-header {
            text-align: center;
            margin-bottom: 40px;
        }
        .installer-header h1 {
            font-size: 2rem;
            font-weight: 700;
            background: linear-gradient(135deg, #6366f1, #8b5cf6, #a855f7);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 8px;
        }
        .installer-header p {
            color: var(--text-secondary);
            font-size: 0.95rem;
        }
        .steps-indicator {
            display: flex;
            justify-content: center;
            gap: 8px;
            margin-bottom: 32px;
        }
        .step-dot {
            width: 40px;
            height: 4px;
            border-radius: 2px;
            background: var(--border-color);
            transition: all 0.3s ease;
        }
        .step-dot.active {
            background: var(--accent);
            box-shadow: 0 0 12px var(--accent-glow);
        }
        .step-dot.completed {
            background: var(--success);
        }
        .installer-card {
            background: var(--bg-card);
            border: 1px solid var(--border-color);
            border-radius: 16px;
            padding: 32px;
            backdrop-filter: blur(20px);
        }
        .installer-card h2 {
            font-size: 1.3rem;
            font-weight: 600;
            margin-bottom: 8px;
        }
        .installer-card .step-desc {
            color: var(--text-secondary);
            font-size: 0.9rem;
            margin-bottom: 24px;
        }
        .form-label {
            color: var(--text-secondary);
            font-size: 0.85rem;
            font-weight: 500;
            margin-bottom: 6px;
        }
        .form-control {
            background: var(--bg-secondary);
            border: 1px solid var(--border-color);
            color: var(--text-primary);
            border-radius: 10px;
            padding: 10px 14px;
            font-size: 0.9rem;
            transition: all 0.2s;
        }
        .form-control:focus {
            background: var(--bg-secondary);
            border-color: var(--accent);
            box-shadow: 0 0 0 3px var(--accent-glow);
            color: var(--text-primary);
        }
        .form-control::placeholder { color: #555; }
        .btn-primary {
            background: linear-gradient(135deg, #6366f1, #8b5cf6);
            border: none;
            border-radius: 10px;
            padding: 10px 24px;
            font-weight: 600;
            transition: all 0.2s;
        }
        .btn-primary:hover {
            transform: translateY(-1px);
            box-shadow: 0 4px 20px var(--accent-glow);
        }
        .btn-secondary {
            background: var(--bg-secondary);
            border: 1px solid var(--border-color);
            color: var(--text-primary);
            border-radius: 10px;
            padding: 10px 24px;
        }
        .req-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 0;
            border-bottom: 1px solid var(--border-color);
        }
        .req-item:last-child { border-bottom: none; }
        .badge-pass { background: rgba(34,197,94,0.15); color: var(--success); padding: 4px 10px; border-radius: 6px; font-size: 0.8rem; }
        .badge-fail { background: rgba(239,68,68,0.15); color: var(--danger); padding: 4px 10px; border-radius: 6px; font-size: 0.8rem; }
        .alert-danger {
            background: rgba(239,68,68,0.1);
            border: 1px solid rgba(239,68,68,0.2);
            color: #fca5a5;
            border-radius: 10px;
            padding: 12px 16px;
            margin-bottom: 16px;
            font-size: 0.9rem;
        }
        .success-icon {
            font-size: 4rem;
            color: var(--success);
            margin-bottom: 16px;
        }
        .cron-code {
            background: var(--bg-secondary);
            border: 1px solid var(--border-color);
            border-radius: 8px;
            padding: 12px;
            font-family: 'SF Mono', monospace;
            font-size: 0.82rem;
            color: var(--success);
            word-break: break-all;
            margin: 8px 0;
        }
    </style>
</head>
<body>
<div class="installer-container">
    <div class="installer-header">
        <h1><i class="bi bi-chat-dots-fill"></i> BulkSMS Pro</h1>
        <p>Installation Wizard</p>
    </div>

    <div class="steps-indicator">
        <?php for ($i = 1; $i <= 5; $i++): ?>
            <div class="step-dot <?= $i < $step ? 'completed' : ($i === $step ? 'active' : '') ?>"></div>
        <?php endfor; ?>
    </div>

    <div class="installer-card">
        <?php if (!empty($errors)): ?>
            <div class="alert-danger">
                <?php foreach ($errors as $err): ?>
                    <div><i class="bi bi-exclamation-circle"></i> <?= htmlspecialchars($err) ?></div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <?php if ($step === 1): ?>
            <!-- Step 1: Welcome -->
            <div class="text-center">
                <div style="font-size:3rem;margin-bottom:16px">
                    <i class="bi bi-rocket-takeoff" style="color:var(--accent)"></i>
                </div>
                <h2>Welcome to BulkSMS Pro</h2>
                <p class="step-desc">Enterprise-grade Bulk SMS Platform. This wizard will guide you through the installation process.</p>
                <div style="text-align:left;margin:24px 0">
                    <div class="req-item"><span>Auto database setup</span><i class="bi bi-check-circle text-success"></i></div>
                    <div class="req-item"><span>Configuration auto-creation</span><i class="bi bi-check-circle text-success"></i></div>
                    <div class="req-item"><span>Admin account setup</span><i class="bi bi-check-circle text-success"></i></div>
                    <div class="req-item"><span>Cron job instructions</span><i class="bi bi-check-circle text-success"></i></div>
                </div>
                <a href="?step=2" class="btn btn-primary w-100">Start Installation <i class="bi bi-arrow-right"></i></a>
            </div>

        <?php elseif ($step === 2): ?>
            <!-- Step 2: Server Requirements -->
            <h2><i class="bi bi-gear"></i> Server Requirements</h2>
            <p class="step-desc">Checking if your server meets all requirements</p>
            <?php foreach ($requirements as $req): ?>
                <div class="req-item">
                    <span><?= htmlspecialchars($req['name']) ?></span>
                    <span class="<?= $req['status'] ? 'badge-pass' : 'badge-fail' ?>">
                        <?= htmlspecialchars($req['current']) ?>
                    </span>
                </div>
            <?php endforeach; ?>
            <div class="d-flex gap-2 mt-4">
                <a href="?step=1" class="btn btn-secondary">Back</a>
                <?php if ($allPassed): ?>
                    <a href="?step=3" class="btn btn-primary flex-fill">Continue <i class="bi bi-arrow-right"></i></a>
                <?php else: ?>
                    <button class="btn btn-primary flex-fill" disabled>Fix Requirements First</button>
                <?php endif; ?>
            </div>

        <?php elseif ($step === 3): ?>
            <!-- Step 3: Database Configuration -->
            <h2><i class="bi bi-database"></i> Database Configuration</h2>
            <p class="step-desc">Enter your MySQL database credentials</p>
            <form method="POST">
                <div class="row g-3">
                    <div class="col-8">
                        <label class="form-label">Database Host</label>
                        <input type="text" class="form-control" name="db_host" value="localhost" required>
                    </div>
                    <div class="col-4">
                        <label class="form-label">Port</label>
                        <input type="text" class="form-control" name="db_port" value="3306" required>
                    </div>
                    <div class="col-12">
                        <label class="form-label">Database Name</label>
                        <input type="text" class="form-control" name="db_name" placeholder="bulksms_db" required>
                    </div>
                    <div class="col-12">
                        <label class="form-label">Database Username</label>
                        <input type="text" class="form-control" name="db_user" placeholder="root" required>
                    </div>
                    <div class="col-12">
                        <label class="form-label">Database Password</label>
                        <input type="password" class="form-control" name="db_pass" placeholder="Enter password">
                    </div>
                </div>
                <div class="d-flex gap-2 mt-4">
                    <a href="?step=2" class="btn btn-secondary">Back</a>
                    <button type="submit" class="btn btn-primary flex-fill">Install Database <i class="bi bi-arrow-right"></i></button>
                </div>
            </form>

        <?php elseif ($step === 4): ?>
            <!-- Step 4: Admin Account -->
            <h2><i class="bi bi-person-badge"></i> Admin Account & Site Setup</h2>
            <p class="step-desc">Create the super admin account and configure site settings</p>
            <form method="POST">
                <div class="row g-3">
                    <div class="col-12">
                        <label class="form-label">Site Name</label>
                        <input type="text" class="form-control" name="site_name" value="BulkSMS Pro" required>
                    </div>
                    <div class="col-12">
                        <label class="form-label">Site URL</label>
                        <input type="url" class="form-control" name="site_url" placeholder="https://yourdomain.com" value="<?= 'http' . (isset($_SERVER['HTTPS']) ? 's' : '') . '://' . $_SERVER['HTTP_HOST'] ?>" required>
                    </div>
                    <div class="col-12">
                        <label class="form-label">Admin Full Name</label>
                        <input type="text" class="form-control" name="admin_name" placeholder="John Doe" required>
                    </div>
                    <div class="col-12">
                        <label class="form-label">Admin Email</label>
                        <input type="email" class="form-control" name="admin_email" placeholder="admin@example.com" required>
                    </div>
                    <div class="col-6">
                        <label class="form-label">Password</label>
                        <input type="password" class="form-control" name="admin_password" minlength="8" required>
                    </div>
                    <div class="col-6">
                        <label class="form-label">Confirm Password</label>
                        <input type="password" class="form-control" name="admin_password_confirm" minlength="8" required>
                    </div>
                </div>
                <div class="d-flex gap-2 mt-4">
                    <a href="?step=3" class="btn btn-secondary">Back</a>
                    <button type="submit" class="btn btn-primary flex-fill">Complete Installation <i class="bi bi-arrow-right"></i></button>
                </div>
            </form>

        <?php elseif ($step === 5): ?>
            <!-- Step 5: Complete -->
            <div class="text-center">
                <div class="success-icon"><i class="bi bi-check-circle-fill"></i></div>
                <h2>Installation Complete!</h2>
                <p class="step-desc">BulkSMS Pro has been installed successfully. Set up the cron jobs below.</p>
            </div>
            <div style="text-align:left;margin-top:20px">
                <h6 class="mb-2" style="color:var(--accent)"><i class="bi bi-clock-history"></i> Required Cron Jobs</h6>
                <p style="font-size:0.85rem;color:var(--text-secondary)">Add these cron jobs in your cPanel &gt; Cron Jobs section:</p>
                <label class="form-label">Queue Worker (every minute):</label>
                <div class="cron-code">* * * * * php <?= ROOT_PATH ?>/cron/queue_worker.php >> <?= ROOT_PATH ?>/storage/logs/cron.log 2>&1</div>
                <label class="form-label">Scheduled SMS (every minute):</label>
                <div class="cron-code">* * * * * php <?= ROOT_PATH ?>/cron/scheduled_sms.php >> <?= ROOT_PATH ?>/storage/logs/cron.log 2>&1</div>
                <label class="form-label">Gateway Health Check (every 5 minutes):</label>
                <div class="cron-code">*/5 * * * * php <?= ROOT_PATH ?>/cron/gateway_health.php >> <?= ROOT_PATH ?>/storage/logs/cron.log 2>&1</div>
                <label class="form-label">Cleanup & Maintenance (daily):</label>
                <div class="cron-code">0 2 * * * php <?= ROOT_PATH ?>/cron/daily_cleanup.php >> <?= ROOT_PATH ?>/storage/logs/cron.log 2>&1</div>
                <label class="form-label">Auto Backup (daily):</label>
                <div class="cron-code">0 3 * * * php <?= ROOT_PATH ?>/cron/backup.php >> <?= ROOT_PATH ?>/storage/logs/cron.log 2>&1</div>
            </div>
            <div class="mt-4 text-center">
                <a href="../public/" class="btn btn-primary btn-lg w-100">
                    <i class="bi bi-box-arrow-in-right"></i> Go to Dashboard
                </a>
                <p class="mt-3" style="font-size:0.8rem;color:var(--text-secondary)">
                    <i class="bi bi-shield-lock"></i> For security, delete the <code>/install</code> folder after installation.
                </p>
            </div>
        <?php endif; ?>
    </div>
</div>
</body>
</html>
